// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// DO NOT EDIT - This file is generated by gen_lang_imports through the gen-lang-imports script

/* eslint-disable */

import en from './en.json';
import ru from './ru.json';
import zhCN from './zh-CN.json';
import zhTW from './zh-TW.json';

type TranslationsMap = {
    [id: string]: string,
};

export const langIDs = ["en","ru","zh-CN","zh-TW"];

export const langLabels = {"en":"English","ru":"Русский","zh-CN":"中文（中国大陆）","zh-TW":"中文"};

export const langFiles: {[langID: string]: TranslationsMap} = {en,ru,'zh-CN':zhCN,'zh-TW':zhTW};